// emenu/src/routes/auth/login/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { page } from '$app/stores';
	import directusAuth, { type DirectusUser } from '$lib/server/auth';

	let email = '';
	let phone = '';
	let password = '';
	let loginMethod: 'email' | 'phone' = 'email';
	let isLoading = false;
	let errorMessage = '';
	let showPassword = false;

	async function handleLogin() {
		if (!password.trim()) {
			errorMessage = 'Password is required';
			return;
		}

		isLoading = true;
		errorMessage = '';

		try {
			let user: DirectusUser;

			if (loginMethod === 'email') {
				if (!email.trim()) {
					errorMessage = 'Email is required';
					isLoading = false;
					return;
				}
				user = await directusAuth.login(email.trim(), password);
			} else {
				if (!phone.trim()) {
					errorMessage = 'Phone number is required';
					isLoading = false;
					return;
				}
				user = await directusAuth.loginWithPhone(phone.trim(), password);
			}

			// Redirect to hub or intended page
			const redirectTo = $page.url.searchParams.get('redirect') || '/hub';
			goto(redirectTo);
		} catch (error) {
			console.error('Login error:', error);
			errorMessage = 'Invalid credentials. Please try again.';
		} finally {
			isLoading = false;
		}
	}

	function formatPhoneNumber(event: Event) {
		const input = event.target as HTMLInputElement;
		let value = input.value.replace(/\D/g, '');

		// Add +84 prefix if not present
		if (!value.startsWith('84')) {
			value = '84' + value;
		}

		// Format as +84 XXX XXX XXX
		if (value.length > 2) {
			value = '+' + value.slice(0, 2) + ' ' + value.slice(2, 5) + ' ' + value.slice(5, 8) + ' ' + value.slice(8, 11);
		}

		input.value = value;
		phone = value;
	}

	function togglePasswordVisibility() {
		showPassword = !showPassword;
	}
</script>

<svelte:head>
	<title>Login - SOL Restaurant Hub</title>
	<meta name="description" content="Login to SOL Restaurant staff management portal" />
</svelte:head>

<div class="min-h-screen bg-gradient-to-br from-cyan-50 to-teal-100 flex items-center justify-center p-4">
	<div class="max-w-md w-full space-y-8">
		<!-- Logo and Header -->
		<div class="text-center">
			<img
				src="/logos/logo_trim.png"
				alt="SOL Restaurant"
				class="mx-auto h-16 w-auto mb-4"
			/>
			<h2 class="text-3xl font-bold text-gray-900">Staff Hub Login</h2>
			<p class="mt-2 text-sm text-gray-600">Sign in to access the restaurant management system</p>
		</div>

		<!-- Login Form -->
		<div class="bg-white shadow-xl rounded-lg p-8">
			<!-- Login Method Toggle -->
			<div class="flex mb-6 bg-gray-100 rounded-lg p-1">
				<button
					class="flex-1 py-2 px-4 text-sm font-medium rounded-md transition-colors {loginMethod === 'email'
						? 'bg-white text-gray-900 shadow-sm'
						: 'text-gray-600 hover:text-gray-900'}"
					on:click={() => (loginMethod = 'email')}
				>
					Email
				</button>
				<button
					class="flex-1 py-2 px-4 text-sm font-medium rounded-md transition-colors {loginMethod === 'phone'
						? 'bg-white text-gray-900 shadow-sm'
						: 'text-gray-600 hover:text-gray-900'}"
					on:click={() => (loginMethod = 'phone')}
				>
					Phone
				</button>
			</div>

			<form on:submit|preventDefault={handleLogin} class="space-y-6">
				<!-- Email/Phone Input -->
				<div>
					<label for="identifier" class="block text-sm font-medium text-gray-700 mb-2">
						{loginMethod === 'email' ? 'Email Address' : 'Phone Number'}
					</label>
					{#if loginMethod === 'email'}
						<input
							id="identifier"
							type="email"
							placeholder="your.email@sol.com.vn"
							bind:value={email}
							class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-cyan-500 focus:border-transparent outline-none transition-all"
							required
						/>
					{:else}
						<input
							id="identifier"
							type="tel"
							placeholder="+84 XXX XXX XXX"
							bind:value={phone}
							on:input={formatPhoneNumber}
							class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-cyan-500 focus:border-transparent outline-none transition-all"
							required
						/>
					{/if}
				</div>

				<!-- Password Input -->
				<div>
					<label for="password" class="block text-sm font-medium text-gray-700 mb-2">
						Password
					</label>
					<div class="relative">
						<input
							id="password"
							type={showPassword ? 'text' : 'password'}
							placeholder="Enter your password"
							bind:value={password}
							class="w-full px-4 py-3 pr-12 border border-gray-300 rounded-lg focus:ring-2 focus:ring-cyan-500 focus:border-transparent outline-none transition-all"
							required
						/>
						<button
							type="button"
							on:click={togglePasswordVisibility}
							class="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-500 hover:text-gray-700"
						>
							{#if showPassword}
								<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21"></path>
								</svg>
							{:else}
								<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path>
								</svg>
							{/if}
						</button>
					</div>
				</div>

				<!-- Error Message -->
				{#if errorMessage}
					<div class="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg text-sm">
						{errorMessage}
					</div>
				{/if}

				<!-- Submit Button -->
				<button
					type="submit"
					disabled={isLoading}
					class="w-full bg-cyan-600 text-white py-3 px-4 rounded-lg hover:bg-cyan-700 focus:ring-4 focus:ring-cyan-200 transition-all font-medium disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center"
				>
					{#if isLoading}
						<svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" fill="none" viewBox="0 0 24 24">
							<circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
							<path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
						</svg>
						Signing in...
					{:else}
						Sign In
					{/if}
				</button>
			</form>

			<!-- Forgot Password Link -->
			<div class="mt-6 text-center">
				<a href="/auth/forgot-password" class="text-sm text-cyan-600 hover:text-cyan-800 font-medium">
					Forgot your password?
				</a>
			</div>
		</div>

		<!-- Footer -->
		<div class="text-center text-sm text-gray-600">
			<p>&copy; 2024 SOL Restaurant. All rights reserved.</p>
			<p class="mt-1">Need help? Contact your system administrator</p>
		</div>
	</div>
</div>

// web-emenu/src/app/[locale]/login/page.tsx
'use client';

import { useState, useEffect, Suspense } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import { useTranslations } from 'next-intl';
import { useLocale } from 'next/navigation';

interface ErrorResponse { error?: string }

function LoginPageContent() {
  const t = useTranslations();
  const locale = useLocale();
  const router = useRouter();
  const search = useSearchParams();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [providers, setProviders] = useState<string[]>([]);
  const [resetLoading, setResetLoading] = useState(false);

  useEffect(() => {
    // Load available OAuth providers
    fetch('/api/auth/providers')
      .then((res) => res.json())
      .then((data) => {
        if (Array.isArray(data.providers)) setProviders(data.providers);
      })
      .catch(() => {});
  }, []);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setLoading(true);
    try {
      const res = await fetch('/api/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, password }),
      });
      if (!res.ok) {
        const data: ErrorResponse = await res.json().catch(() => ({} as ErrorResponse));
        throw new Error(data.error || 'Invalid credentials');
      }
      toast.success(t('auth.success'));
      const redirect = search.get('redirect') || `/${locale}/portal`;
      router.push(redirect);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Login failed');
    } finally {
      setLoading(false);
    }
  }

  async function handleForgotPassword() {
    if (!email) {
      return toast.error('Please enter your email to reset password');
    }
    setResetLoading(true);
    try {
      const reset_url = `${window.location.origin}/reset-password`;
      const res = await fetch('/api/auth/password/request', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, reset_url }),
      });
      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error(data.error || 'Failed to send reset email');
      }
      toast.success('Password reset email sent. Check your inbox.');
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Failed to send reset email');
    } finally {
      setResetLoading(false);
    }
  }

  return (
    <div className="min-h-screen bg-gray-50 flex">
      {/* Sidebar - Pre-auth */}
      <aside className="hidden md:flex w-72 bg-gradient-to-b from-orange-50 to-rose-50 border-r border-gray-200 p-6">
        <div className="flex flex-col gap-4 w-full">
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-3">
              <img src="/logo_trim.png" alt="SOL eMenu" className="h-10 w-auto" />
              <div>
                <div className="text-xl font-bold tracking-tight text-gray-900">SOL eMenu</div>
                <div className="text-xs text-gray-500">{t('portal.dashboard')}</div>
              </div>
            </div>
            <button
              onClick={() => router.push(locale === 'en' ? '/vi/login' : '/en/login')}
              className="p-2 text-gray-500 hover:text-gray-700 hover:bg-white/60 rounded-md transition-colors"
              title={t('auth.language')}
            >
              🌐 {locale === 'en' ? 'EN' : 'VI'}
            </button>
          </div>
          <nav className="flex flex-col gap-2 text-sm text-gray-700">
            <span className="font-semibold text-gray-900">{t('auth.welcomeBack')}</span>
            <span className="text-gray-600">{t('auth.loginDescription')}</span>
          </nav>
          <div className="mt-4">
            <div className="text-xs uppercase text-gray-400 mb-2">Quick Links</div>
            <div className="flex flex-col gap-1 text-sm">
              <a className="flex items-center gap-2 rounded-md px-3 py-2 hover:bg-white/60 hover:text-black" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 15a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4"/><path d="M3 15a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4"/><path d="M7 11V7a5 5 0 1 1 10 0v4"/></svg>
                <span>Support</span>
              </a>
              <a className="flex items-center gap-2 rounded-md px-3 py-2 hover:bg-white/60 hover:text-black" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 10a9 9 0 1 1-18 0"/><path d="M12 6v6l4 2"/></svg>
                <span>Contact</span>
              </a>
            </div>
          </div>
        </div>
      </aside>

      <main className="flex-1 flex items-center justify-center p-6">
        <Card className="w-full max-w-md shadow-sm">
          <CardHeader>
            <CardTitle>{t('auth.login')}</CardTitle>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <Label htmlFor="email">{t('auth.email')}</Label>
                <Input
                  id="email"
                  type="email"
                  placeholder="you@example.com"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                />
              </div>
              <div>
                <Label htmlFor="password">{t('auth.password')}</Label>
                <Input
                  id="password"
                  type="password"
                  placeholder="••••••••"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                />
              </div>
              <div className="flex items-center justify-between">
                <Button type="submit" className="w-full" disabled={loading}>
                  {loading ? t('common.loading') : t('auth.login')}
                </Button>
              </div>
            </form>

            <div className="mt-4 flex items-center justify-between">
              <Button variant="link" type="button" onClick={handleForgotPassword} disabled={resetLoading}>
                {resetLoading ? t('common.loading') : t('auth.forgotPassword')}
              </Button>
            </div>

            {providers.length > 0 && (
              <div className="mt-6">
                <div className="text-sm text-gray-600 mb-2">Or sign in with</div>
                <div className="flex flex-wrap gap-2">
                  {providers.map((p) => (
                    <Button key={p} variant="outline" type="button" onClick={() => router.push(`/api/auth/oauth/${p}`)}>
                      {p}
                    </Button>
                  ))}
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      </main>
    </div>
  );
}

export default function LoginPage() {
  return (
    <Suspense fallback={<div className="min-h-screen bg-gray-50 flex items-center justify-center"><div>Loading...</div></div>}>
      <LoginPageContent />
    </Suspense>
  );
}
