// emenu/src/routes/auth/login/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { page } from '$app/stores';
	import directusAuth, { type DirectusUser } from '$lib/server/auth';

	let email = '';
	let phone = '';
	let password = '';
	let loginMethod: 'email' | 'phone' = 'email';
	let isLoading = false;
	let errorMessage = '';
	let showPassword = false;

	async function handleLogin() {
		if (!password.trim()) {
			errorMessage = 'Password is required';
			return;
		}

		isLoading = true;
		errorMessage = '';

		try {
			let user: DirectusUser;

			if (loginMethod === 'email') {
				if (!email.trim()) {
					errorMessage = 'Email is required';
					isLoading = false;
					return;
				}
				user = await directusAuth.login(email.trim(), password);
			} else {
				if (!phone.trim()) {
					errorMessage = 'Phone number is required';
					isLoading = false;
					return;
				}
				user = await directusAuth.loginWithPhone(phone.trim(), password);
			}

			// Redirect to hub or intended page
			const redirectTo = $page.url.searchParams.get('redirect') || '/hub';
			goto(redirectTo);
		} catch (error) {
			console.error('Login error:', error);
			errorMessage = 'Invalid credentials. Please try again.';
		} finally {
			isLoading = false;
		}
	}

	function formatPhoneNumber(event: Event) {
		const input = event.target as HTMLInputElement;
		let value = input.value.replace(/\D/g, '');

		// Add +84 prefix if not present
		if (!value.startsWith('84')) {
			value = '84' + value;
		}

		// Format as +84 XXX XXX XXX
		if (value.length > 2) {
			value = '+' + value.slice(0, 2) + ' ' + value.slice(2, 5) + ' ' + value.slice(5, 8) + ' ' + value.slice(8, 11);
		}

		input.value = value;
		phone = value;
	}

	function togglePasswordVisibility() {
		showPassword = !showPassword;
	}
</script>

<svelte:head>
	<title>Login - SOL Restaurant Hub</title>
	<meta name="description" content="Login to SOL Restaurant staff management portal" />
</svelte:head>

<div class="min-h-screen bg-gradient-to-br from-cyan-50 to-teal-100 flex items-center justify-center p-4">
	<div class="max-w-md w-full space-y-8">
		<!-- Logo and Header -->
		<div class="text-center">
			<img
				src="/logos/logo_trim.png"
				alt="SOL Restaurant"
				class="mx-auto h-16 w-auto mb-4"
			/>
			<h2 class="text-3xl font-bold text-gray-900">Staff Hub Login</h2>
			<p class="mt-2 text-sm text-gray-600">Sign in to access the restaurant management system</p>
		</div>

		<!-- Login Form -->
		<div class="bg-white shadow-xl rounded-lg p-8">
			<!-- Login Method Toggle -->
			<div class="flex mb-6 bg-gray-100 rounded-lg p-1">
				<button
					class="flex-1 py-2 px-4 text-sm font-medium rounded-md transition-colors {loginMethod === 'email'
						? 'bg-white text-gray-900 shadow-sm'
						: 'text-gray-600 hover:text-gray-900'}"
					on:click={() => (loginMethod = 'email')}
				>
					Email
				</button>
				<button
					class="flex-1 py-2 px-4 text-sm font-medium rounded-md transition-colors {loginMethod === 'phone'
						? 'bg-white text-gray-900 shadow-sm'
						: 'text-gray-600 hover:text-gray-900'}"
					on:click={() => (loginMethod = 'phone')}
				>
					Phone
				</button>
			</div>

			<form on:submit|preventDefault={handleLogin} class="space-y-6">
				<!-- Email/Phone Input -->
				<div>
					<label for="identifier" class="block text-sm font-medium text-gray-700 mb-2">
						{loginMethod === 'email' ? 'Email Address' : 'Phone Number'}
					</label>
					{#if loginMethod === 'email'}
						<input
							id="identifier"
							type="email"
							placeholder="your.email@sol.com.vn"
							bind:value={email}
							class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-cyan-500 focus:border-transparent outline-none transition-all"
							required
						/>
					{:else}
						<input
							id="identifier"
							type="tel"
							placeholder="+84 XXX XXX XXX"
							bind:value={phone}
							on:input={formatPhoneNumber}
							class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-cyan-500 focus:border-transparent outline-none transition-all"
							required
						/>
					{/if}
				</div>

				<!-- Password Input -->
				<div>
					<label for="password" class="block text-sm font-medium text-gray-700 mb-2">
						Password
					</label>
					<div class="relative">
						<input
							id="password"
							type={showPassword ? 'text' : 'password'}
							placeholder="Enter your password"
							bind:value={password}
							class="w-full px-4 py-3 pr-12 border border-gray-300 rounded-lg focus:ring-2 focus:ring-cyan-500 focus:border-transparent outline-none transition-all"
							required
						/>
						<button
							type="button"
							on:click={togglePasswordVisibility}
							class="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-500 hover:text-gray-700"
						>
							{#if showPassword}
								<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21"></path>
								</svg>
							{:else}
								<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path>
								</svg>
							{/if}
						</button>
					</div>
				</div>

				<!-- Error Message -->
				{#if errorMessage}
					<div class="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg text-sm">
						{errorMessage}
					</div>
				{/if}

				<!-- Submit Button -->
				<button
					type="submit"
					disabled={isLoading}
					class="w-full bg-cyan-600 text-white py-3 px-4 rounded-lg hover:bg-cyan-700 focus:ring-4 focus:ring-cyan-200 transition-all font-medium disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center"
				>
					{#if isLoading}
						<svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" fill="none" viewBox="0 0 24 24">
							<circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
							<path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
						</svg>
						Signing in...
					{:else}
						Sign In
					{/if}
				</button>
			</form>

			<!-- Forgot Password Link -->
			<div class="mt-6 text-center">
				<a href="/auth/forgot-password" class="text-sm text-cyan-600 hover:text-cyan-800 font-medium">
					Forgot your password?
				</a>
			</div>
		</div>

		<!-- Footer -->
		<div class="text-center text-sm text-gray-600">
			<p>&copy; 2024 SOL Restaurant. All rights reserved.</p>
			<p class="mt-1">Need help? Contact your system administrator</p>
		</div>
	</div>
</div>

// emenu/src/app/login/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { useAuth } from '@/contexts/AuthContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Checkbox } from '@/components/ui/checkbox';
import { Separator } from '@/components/ui/separator';
import { Badge } from '@/components/ui/badge';
import { Loader2, Eye, EyeOff, Lock, Mail, Shield } from 'lucide-react';
import LoadingSpinner from '@/components/ui/LoadingSpinner';

export default function LoginPage() {
	const [email, setEmail] = useState('');
	const [password, setPassword] = useState('');
	const [showPassword, setShowPassword] = useState(false);
	const [rememberMe, setRememberMe] = useState(false);
	const [isLoading, setIsLoading] = useState(false);
	const [error, setError] = useState('');

	const { login, isAuthenticated } = useAuth();
	const router = useRouter();
	const searchParams = useSearchParams();
	
	// Get redirect URL from query params
	const redirectTo = searchParams.get('redirect') || '/hub';

	// Load saved credentials on mount
	useEffect(() => {
		const savedEmail = localStorage.getItem('remembered_email');
		const savedRememberMe = localStorage.getItem('remember_me') === 'true';

		if (savedEmail && savedRememberMe) {
			setEmail(savedEmail);
			setRememberMe(true);
		}
	}, []);

	// Redirect if already authenticated
	useEffect(() => {
		if (isAuthenticated) {
			router.push(redirectTo);
		}
	}, [isAuthenticated, router, redirectTo]);

	const handleSubmit = async (e: React.FormEvent) => {
		e.preventDefault();
		setIsLoading(true);
		setError('');

		try {
			const result = await login(email, password, rememberMe);

			if (result.success) {
				// Save email if remember me is checked
				if (rememberMe) {
					localStorage.setItem('remembered_email', email);
					localStorage.setItem('remember_me', 'true');
				} else {
					localStorage.removeItem('remembered_email');
					localStorage.removeItem('remember_me');
				}

				// Use window.location for a full page refresh to ensure cookies are properly set
				window.location.href = redirectTo;
			} else {
				setError(result.error || 'Login failed');
			}
		} catch (err) {
			setError('An unexpected error occurred');
		} finally {
			setIsLoading(false);
		}
	};

	return (
		<div className="min-h-screen bg-white flex flex-col">
			{/* Responsive Header */}
			<header className="border-b bg-white/95 backdrop-blur supports-[backdrop-filter]:bg-white/60">
				<div className="container mx-auto px-4 sm:px-6 lg:px-8">
					<div className="flex h-16 items-center justify-between">
						<div className="flex items-center space-x-4">
							<img
								className="h-10 w-auto sm:h-12"
								src="/images/logo_trim.png"
								alt="SOL eMenu"
							/>
						</div>
						<div className="flex items-center space-x-2">
							<Shield className="h-4 w-4 text-gray-600" />
							<span className="text-sm text-gray-600 hidden sm:inline">
								Secure Login
							</span>
						</div>
					</div>
				</div>
			</header>

			{/* Main Content */}
			<main className="flex-1 flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
				<div className="w-full max-w-md">
					{/* Welcome Section */}
					<div className="text-center mb-8">
						<div className="flex justify-center mb-4">
							<div className="w-12 h-12 bg-primary/10 rounded-full flex items-center justify-center">
								<Lock className="h-6 w-6 text-primary" />
							</div>
						</div>
						<h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-gray-900">
							Welcome back
						</h1>
						<p className="mt-2 text-sm text-gray-600">
							Sign in to access the SOL eMenu dashboard
						</p>
					</div>

					{/* Login Card */}
					<Card className="border-0 shadow-lg">
						<CardHeader className="space-y-1 pb-4">
							<CardTitle className="text-xl text-center text-gray-900 font-semibold">Sign In</CardTitle>
							<CardDescription className="text-center text-gray-600">
								Enter your credentials to continue
							</CardDescription>
						</CardHeader>

						<form onSubmit={handleSubmit}>
							<CardContent className="space-y-4">
								{error && (
									<Alert variant="destructive">
										<AlertDescription>{error}</AlertDescription>
									</Alert>
								)}

								<div className="space-y-2">
									<Label htmlFor="email" className="flex items-center gap-2 text-gray-900">
										<Mail className="h-4 w-4" />
										Email Address
									</Label>
									<Input
										id="email"
										type="email"
										value={email}
										onChange={(e) => setEmail(e.target.value)}
										placeholder="name@example.com"
										required
										disabled={isLoading}
										className="h-11 bg-white text-gray-900 border-gray-300"
									/>
								</div>

								<div className="space-y-2">
									<Label htmlFor="password" className="flex items-center gap-2 text-gray-900">
										<Lock className="h-4 w-4" />
										Password
									</Label>
									<div className="relative">
										<Input
											id="password"
											type={showPassword ? 'text' : 'password'}
											value={password}
											onChange={(e) => setPassword(e.target.value)}
											placeholder="Enter your password"
											required
											disabled={isLoading}
											className="h-11 pr-12 bg-white text-gray-900 border-gray-300"
										/>
										<Button
											type="button"
											variant="ghost"
											size="sm"
											className="absolute right-0 top-0 h-full px-3 py-2 hover:bg-transparent"
											onClick={() => setShowPassword(!showPassword)}
											disabled={isLoading}
										>
											{showPassword ? (
												<EyeOff className="h-4 w-4 text-gray-600" />
											) : (
												<Eye className="h-4 w-4 text-gray-600" />
											)}
										</Button>
									</div>
								</div>

								<div className="flex items-center justify-between">
									<div className="flex items-center space-x-2">
										<Checkbox
											id="remember-me"
											checked={rememberMe}
											onCheckedChange={(checked) => setRememberMe(checked as boolean)}
											disabled={isLoading}
										/>
										<Label
											htmlFor="remember-me"
											className="text-sm font-medium cursor-pointer text-gray-900"
										>
											Remember me
										</Label>
									</div>
								</div>
							</CardContent>

							<CardFooter className="flex flex-col space-y-4 pt-6">
								<Button
									type="submit"
									className="w-full h-11"
									disabled={isLoading}
								>
									{isLoading ? (
										<>
											<Loader2 className="mr-2 h-4 w-4 animate-spin" />
											Signing in...
										</>
									) : (
										'Sign In'
									)}
								</Button>
							</CardFooter>
						</form>
					</Card>

					{/* Help Section */}
					<div className="mt-8 text-center">
						<div className="space-y-4">
							<Separator className="max-w-xs mx-auto" />
							<div className="space-y-2">
								<p className="text-sm text-gray-600">
									Need assistance with your account?
								</p>
								<div className="flex flex-col sm:flex-row items-center justify-center gap-4 text-sm">
									<Button variant="link" className="h-auto p-0 text-gray-900 hover:text-red-600">
										Contact Administrator
									</Button>
									<span className="text-gray-500 hidden sm:inline">•</span>
									<Button variant="link" className="h-auto p-0 text-gray-900 hover:text-red-600">
										System Support
									</Button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</main>

			{/* Footer */}
			<footer className="border-t bg-gray-50">
				<div className="container mx-auto px-4 sm:px-6 lg:px-8">
					<div className="flex h-14 items-center justify-center">
						<p className="text-xs text-gray-600">
							© 2025 SOL eMenu. All rights reserved.
						</p>
					</div>
				</div>
			</footer>
		</div>
	);
}
